import { BALLOON_HUD_START_SRC, BALLOON_HUD_STOP_SRC } from "./balloonHudArt";
import { BALLOON_REWARD_ICON_PLACEHOLDER, BALLOON_REWARDS_ART_SRC, BALLOON_REWARDS_DETAIL_ART_SRC } from "./balloonRewardsArt";
import {
  BONUS_CHART_SRC,
  CASTLE_HEDGES_SRC,
  CASTLE_MODEL_SRC,
  GRASS_GROUND_SRC,
  LEADERBOARD_BLOWERS_SRC,
  LEADERBOARD_POPPERS_SRC,
  SOCIAL_BOOST_BANNER_SRC,
  WALKWAY_SRC,
} from "./castleLayout";
import { CHEST_ROOT_ICON_SRC, DEPOSIT_PICKER_ICON_SRC } from "./chestRoot";
import { DEPOSIT_BG_SRC } from "./chestUiLayout";
import { NPC_GREETING_PORTRAIT_SRC } from "./helpWanted";
import { HELP_WANTED_ART_SRC } from "./helpWantedArt";
import { LEARN_MORE_ART_SRC } from "./learnMoreArt";
import { NEXT_DROP_TICKER_SRC } from "./nextDropTicker";
import { POP_BUTTON_IMAGE_SRC } from "./popUi";
import {
  MUSIC_ICON_NEXT_SRC,
  MUSIC_ICON_PLAY_SRC,
  MUSIC_ICON_STOP_SRC,
  MUSIC_ICON_VOL_DOWN_SRC,
  MUSIC_ICON_VOL_UP_SRC,
} from "./sceneMusic";
import { BALLOON_CAPTCHA_SHAPES, balloonCaptchaSrc } from "./turnInCaptcha";
import { TURN_IN_ART_SRC } from "./turnInBalloonsArt";
import { MANA_TOKEN_ICON_SRC } from "./wins";

function uniqueSceneTextures(srcs: readonly string[]): readonly string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const src of srcs) {
    if (seen.has(src)) continue;
    seen.add(src);
    out.push(src);
  }
  return out;
}

/**
 * First-paint world shell. AssetLoad these before any other scene files so the
 * castle, hedges, lawn, and road win the download queue.
 */
export const PRELOAD_SCENE_SHELL: readonly string[] = uniqueSceneTextures([
  CASTLE_MODEL_SRC,
  CASTLE_HEDGES_SRC,
  GRASS_GROUND_SRC,
  WALKWAY_SRC,
]);

/**
 * Scene-local textures that React ECS or world materials mount later.
 * Explorer issues GetTextureWebRequest on first use; 525 retries look like a
 * ~10s stall. Keep this list scene files only (not NFT / remote win URLs).
 * Shell textures live in PRELOAD_SCENE_SHELL so they are not re-queued here.
 */
export const PRELOAD_UI_TEXTURES: readonly string[] = uniqueSceneTextures([
  HELP_WANTED_ART_SRC,
  NPC_GREETING_PORTRAIT_SRC,
  BALLOON_HUD_START_SRC,
  BALLOON_HUD_STOP_SRC,
  NEXT_DROP_TICKER_SRC,
  POP_BUTTON_IMAGE_SRC,
  TURN_IN_ART_SRC,
  LEARN_MORE_ART_SRC,
  DEPOSIT_BG_SRC,
  CHEST_ROOT_ICON_SRC.deposit,
  CHEST_ROOT_ICON_SRC.upcoming,
  CHEST_ROOT_ICON_SRC.wins,
  CHEST_ROOT_ICON_SRC.mine,
  DEPOSIT_PICKER_ICON_SRC.wearable,
  DEPOSIT_PICKER_ICON_SRC.emote,
  DEPOSIT_PICKER_ICON_SRC.MANA,
  MUSIC_ICON_STOP_SRC,
  MUSIC_ICON_PLAY_SRC,
  MUSIC_ICON_NEXT_SRC,
  MUSIC_ICON_VOL_DOWN_SRC,
  MUSIC_ICON_VOL_UP_SRC,
  BALLOON_REWARDS_ART_SRC,
  BALLOON_REWARDS_DETAIL_ART_SRC,
  BALLOON_REWARD_ICON_PLACEHOLDER,
  MANA_TOKEN_ICON_SRC,
  ...BALLOON_CAPTCHA_SHAPES.map(balloonCaptchaSrc),
  LEADERBOARD_BLOWERS_SRC,
  LEADERBOARD_POPPERS_SRC,
  SOCIAL_BOOST_BANNER_SRC,
  BONUS_CHART_SRC,
  "assets/images/icon_createParty.png",
  "assets/images/icon_depositNfts.png",
  "assets/images/scene-thumbnail.png",
  "assets/images/autogenerated-thumbnail.png",
]);
